name: build

on:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Prepare for JUCE
        run: |
          sudo apt-get update
          sudo apt install libfontconfig1-dev libasound2-dev libx11-dev libxcomposite-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev libfreetype6-dev libglu1-mesa-dev libjack-jackd2-dev
      - name: Run CMake
        run: |
          cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Release
          cmake --build ./build --config Release --parallel 3

      - name: Show Directory
        run: |
          ls -l ./build/LIVECUTREDUX_artefacts/Release
          
      - name: Build Cleanup
        run: |
          rm ./build/LIVECUTREDUX_artefacts/Release/libLiveCut-Redux_SharedCode.a

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./build/LIVECUTREDUX_artefacts/Release
          name: LiveCut-Redux-v0.0.1-ubuntu-latest-release

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run CMake
        run: |
          cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Release
          cmake --build ./build --config Release --parallel 3

      - name: Show Directory
        run: |
          ls -l ./build/LIVECUTREDUX_artefacts/Release
          
      - name: Build Cleanup
        run: |
          rm ./build/LIVECUTREDUX_artefacts/Release/LiveCut-Redux_SharedCode.lib
          rm ./build/LIVECUTREDUX_artefacts/Release/VST3/LiveCut-Redux.exp
          rm ./build/LIVECUTREDUX_artefacts/Release/VST3/LiveCut-Redux.lib
          rm ./build/LIVECUTREDUX_artefacts/Release/CLAP/LiveCut-Redux.exp
          rm ./build/LIVECUTREDUX_artefacts/Release/CLAP/LiveCut-Redux.lib

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./build/LIVECUTREDUX_artefacts/Release
          name: LiveCut-Redux-v0.0.1-windows-latest-release

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run CMake
        run: |
          cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
          cmake --build ./build --config Release --parallel 3

      - name: Show Directory
        run: |
          ls -l ./build/LIVECUTREDUX_artefacts/Release
          
      - name: Build Cleanup
        run: |
          rm ./build/LIVECUTREDUX_artefacts/Release/libLiveCut-Redux_SharedCode.a

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./build/LIVECUTREDUX_artefacts/Release
          name: LiveCutRedux-v0.0.1-macos-latest-release
